  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module tictactoe::game_won_event {

  use sui::event;

  use std::ascii::String;

  public struct GameWonEvent has copy, drop {
    player: address,
    player_new_total_score: u256,
  }

  public fun new(player: address, player_new_total_score: u256): GameWonEvent {
    GameWonEvent {
                                   player,player_new_total_score
                               }
  }
}
