  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module tictactoe::events {

  use std::ascii::{String, string};

  use tictactoe::game_won_event::GameWonEvent;

  use tictactoe::game_won_event;

  public fun game_won_event(player: address, player_new_total_score: u256) {
    dubhe::storage_event::emit_set_record<GameWonEvent, GameWonEvent, GameWonEvent>(
				string(b"game_won_event"),
				option::none(),
			  	option::none(),
			  option::some(game_won_event::new(player,player_new_total_score))
			  )
  }
}
