  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module tictactoe::schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::storage;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use sui::dynamic_field as df;

  public struct Schema has key, store {
    id: UID,
  }

  public fun borrow_leaderboard(self: &Schema): &StorageMap<address, u256> {
    storage::borrow_field(&self.id, b"leaderboard")
  }

  public(package) fun leaderboard(self: &mut Schema): &mut StorageMap<address, u256> {
    storage::borrow_mut_field(&mut self.id, b"leaderboard")
  }

  public(package) fun create(ctx: &mut TxContext): Schema {
    let mut id = object::new(ctx);
    storage::add_field<StorageMap<address, u256>>(&mut id, b"leaderboard", storage_map::new(b"leaderboard", ctx));
    Schema { id }
  }

  public fun migrate(_schema: &mut Schema, _cap: &UpgradeCap, _ctx: &mut TxContext) {}

  // ======================================== View Functions ========================================

  public fun get_leaderboard(self: &Schema, key: address): &u256 {
    self.borrow_leaderboard().get(key)
  }

  // =========================================================================================================
}
